//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGuide.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travels
    {
        public Travels()
        {
            this.Excursions = new HashSet<Excursions>();
            this.Places = new HashSet<Places>();
            this.Properties = new HashSet<Properties>();
            this.User_Purchased_Travel = new HashSet<User_Purchased_Travel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string CreatorId { get; set; }
        public string ApproverId { get; set; }
        public bool ApprovalStatus { get; set; }
        public string Language { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual ICollection<Excursions> Excursions { get; set; }
        public virtual ICollection<Places> Places { get; set; }
        public virtual ICollection<Properties> Properties { get; set; }
        public virtual ICollection<User_Purchased_Travel> User_Purchased_Travel { get; set; }
    }
}
