//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGuide.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursions
    {
        public Excursions()
        {
            this.Place_Excursion = new HashSet<Place_Excursion>();
            this.Properties = new HashSet<Properties>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<int> Travel_Id { get; set; }
    
        public virtual Travels Travels { get; set; }
        public virtual ICollection<Place_Excursion> Place_Excursion { get; set; }
        public virtual ICollection<Properties> Properties { get; set; }
    }
}
