//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGuide.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VirtualGuideEntities : DbContext
    {
        public VirtualGuideEntities()
            : base("name=VirtualGuideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Excursions> Excursions { get; set; }
        public virtual DbSet<Place_Excursion> Place_Excursion { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<Travels> Travels { get; set; }
        public virtual DbSet<User_Purchased_Travel> User_Purchased_Travel { get; set; }
    }
}
