//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualGuide.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public Places()
        {
            this.Place_Excursion = new HashSet<Place_Excursion>();
            this.Places1 = new HashSet<Places>();
            this.Properties = new HashSet<Properties>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Gps { get; set; }
        public double Radius { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<int> Travel_Id { get; set; }
    
        public virtual ICollection<Place_Excursion> Place_Excursion { get; set; }
        public virtual ICollection<Places> Places1 { get; set; }
        public virtual Places Places2 { get; set; }
        public virtual Travels Travels { get; set; }
        public virtual ICollection<Properties> Properties { get; set; }
    }
}
