app.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', {
        'Sign In': 'Sign In',
        'Email': 'Email',
        'Password': 'Password',
        'Sign me in': 'Sign me in',
        'Hello': 'Hello',
        'Profile': 'Profile',
        'My profile': 'My profile',
        'Sign out': 'Sign out',
        'Online': 'Online',
        'Guides': 'Guides',
        'Show': 'Show',
        'Add': 'Add',
        'Change password': 'Change password',
        'Statistics': 'Statistics',
        'HelloNote': 'In this panel you can add and review your guides.',
        'View Travels': 'View Travels',
        'Start': 'Start',
        'Guide': 'Guide',
        'Guide Wizard': 'Guide Wizard',
        'Show': 'Show',
        'Icon': 'Icon',
        'Name': 'Name',
        'Description': 'Description',
        'Price': 'Price',
        'Approved': 'Approved',
        'Action': 'Action',
        'Edit': 'Edit',
        'Save': 'Save',
        'Cancel': 'Cancel',
        'Enter name for your guide': 'Enter name for your guide',
        'Enter short description': 'Enter short description',
        'Enter price': 'Enter price',
        'Browse': 'Browse',
        'Enter title': 'Enter title',
        'Enter description': 'Enter description',
        'Delete': 'Delete',
        'Add property': 'Add property',
        'Places': 'Places',
        'Add place': 'Add place',
        'Click on the map to add new place': 'Click on the map to add new place',
        'Now, fill the information about the place below': 'Now, fill the information about the place below',
        'Category': 'Category',
        'Enter name for this place': 'Enter name for this place',
        'Enter description about the place such as history or interesting facts': 'Enter description about the place such as history or interesting facts',
        'Choose category': 'Choose category',
        'Show on Map': 'Show on Map',
        'Close': 'Close',
        'Choose symbol': 'Choose symbol',
        'Save and continue': 'Save and continue',
        'Add properties': 'Add properties',
        'CongratulationsProperties': 'Congratulations! You have added a new guide. Now it\'s time to add some more information about this place. Start with adding information such as history or practical tips.',
        'Title': 'Title',
        'Choose': 'Choose',
        'Change': 'Change',
        'Remove this property': 'Remove this property',
        'Add Places': 'Add Places',
        'CongratulationsPlaces': 'Now it\'s time to add some places worth seeing in the location. Start adding by clicking or tapping a place on the map. You can also use the search box.',
        'NoTravelsMsg': 'It\'s lonely here. Add a new guide using the add guide button.',

    });

    $translateProvider.translations('pl', {
        'Sign In': 'Logowanie',
        'Email': 'Email',
        'Password': 'Hasło',
        'Sign me in': 'Zaloguj',
        'Hello': 'Witaj',
        'Profile': 'Profil',
        'My profile': 'Mój profil',
        'Sign out': 'Wyloguj',
        'Online': 'Online',
        'Guides': 'Przewodniki',
        'Show': 'Pokaż',
        'Add': 'Dodaj',
        'Change password': 'Zmień hasło',
        'Statistics': 'Statystyki',
        'HelloNote': 'W tym panelu możesz przeglądać i dodawać nowe przewodniki dla swoich użytkowników.',
        'View Travels': 'Zobacz przewodniki',
        'Start': 'Start',
        'Guide': 'Przewodnik',
        'Guide Wizard': 'Kreator przewodnika',
        'Show': 'Pokaż',
        'Icon': 'Icon',
        'Name': 'Nazwa',
        'Description': 'Opis',
        'Price': 'Cena',
        'Approved': 'Zaaprobowany',
        'Cancel': 'Anuluj',
        'Action': 'Akcje',
        'Edit': 'Edytuj',
        'Save': 'Zapisz',
        'Enter name for your guide': 'Wpisz nazwę swojego przewodnika',
        'Enter short description': 'Wpisz krótki opis',
        'Enter price': 'Wpisz cenę',
        'Browse': 'Wybierz',
        'Enter title': 'Wpisz tytuł',
        'Enter description': 'Wpisz opis',
        'Delete': 'Usuń',
        'Add property': 'Dodaj atrybut',
        'Places': 'Miejsca',
        'Add place': 'Dodaj miejsce',
        'Click on the map to add new place': 'Kliknij na mapie aby dodać nowe miejsce',
        'Now, fill the information about the place below': 'Teraz uzupełnij informacje na temat nowego miejsca',
        'Category': 'Kategoria',
        'Enter name for this place': 'Wpisz nazwę tego miejsca',
        'Enter description about the place such as history or interesting facts': 'Dodaj opis miejsca np. historia lub interesujące fakty',
        'Choose category': 'Wybierz kategorię',
        'Show on Map': 'Pokaż na mapie',
        'Close': 'Zamknij',
        'Choose symbol': 'Wybierz symbol',
        'Save and continue': 'Zapisz i kontynuuj',
        'Add properties': 'Dodaj atrybuty',
        'CongratulationsProperties': 'Gratulacje! Właśnie dodałeś nowy przewodnik. Teraz dodaj nieco więcej informacji o tym miejscu. Możesz rozpocząć od dodania historii lub wskazówek praktycznych.',
        'Title': 'Tytuł',
        'Choose': 'Wybierz',
        'Change': 'Zmień',
        'Remove this property': 'Usuń ten atrybut',
        'Add Places': 'Dodaj miejsca',
        'CongratulationsPlaces': 'Teraz dodaj warte zobaczenia miejsca. Rozpocznij klikając w odpowiednie miejsce na mapie. Możesz też skorzystać z wyszukiwarki.',
        'NoTravelsMsg': 'Pusto tutaj. Dodaj nowy przewodnik korzystając z przycisku na górze strony',

    });

    $translateProvider.preferredLanguage('pl');
    //$translateProvider.determinePreferredLanguage();
}]);